name: Latest Medium posts
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  update-medium-post:
    name: Update latest Medium posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://medium.com/feed/@fahmifj"
