name: Latest blog
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  update-readme-with-personal-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "PERSONAL-BLOG"
          commit_message: "Updated readme with the latest blog posts"
          max_post_count: "3"
          feed_list: "https://fahmifj.github.io/index.xml"
